development:
  clients:
    default:
      database: myapp_development
      hosts:
        - "mongo-service"
      options:
production:
  clients:
      default:
      database: myapp_production
      hosts:
          - localhost:27017
      options:
          connect_timeout: 15